/*
Model downloaded from https://www.mixamo.com/ -> saved as .glb file in Blender -> code below Auto-generated by: https://github.com/pmndrs/gltfjsx -> edited to turn it into a working component
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const LandingAvatar = () => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('models/LandingAvatar.glb');

  console.log(animations);

  animations[0].name = "Landing";

  const { actions } = useAnimations(animations, group);

//   useFrame(() => {
//     group.current.getObjectByName("Head").lookAt(state.camera.position); Head follow - not necessary
//   });

  useEffect(() => { 
    actions["Landing"].reset().play(); // Animation active
  }, []);

  return (
    <group ref={group}>
      <group name="Scene">
        <group name="Armature" position={[0, 0, 1.3]} rotation={[Math.PI / 2.25, 0, 0]} scale={0.005, 0.005, 0.005}>
          <skinnedMesh
            name="Ch03"
            geometry={nodes.Ch03.geometry}
            material={materials.Ch03_Body}
            skeleton={nodes.Ch03.skeleton}
          />
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/LandingAvatar.glb')

export default LandingAvatar
