/*
Model downloaded from https://www.mixamo.com/#/?page=1&query=running -> saved as .glb file in Blender -> code below Auto-generated by: https://github.com/pmndrs/gltfjsx -> edited to turn it into a working component
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import Running from '/models/Running.glb?url'
import { a } from '@react-spring/three'

const RainAvatar = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('models/Running.glb');
  const { actions } = useAnimations(animations, group);

  return (
    <a.group ref={group} {...props}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.02, 0.02, 0.02}>
          <skinnedMesh
            name="Ch03"
            geometry={nodes.Ch03.geometry}
            material={materials.Ch03_Body}
            skeleton={nodes.Ch03.skeleton}
          />
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </a.group>
  )
}

useGLTF.preload('models/Running.glb')

export default RainAvatar