/*
Model downloaded from https://www.mixamo.com/#/?page=1&query=running -> saved as .glb file in Blender -> code below Auto-generated by: https://github.com/pmndrs/gltfjsx -> edited to turn it into a working component
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
// import StormAvatar from '/models/StormAvatar.glb?url'

const StormAvatar = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('models/StormAvatar.glb');

  console.log(animations);

  animations[0].name = "Storm";

  const { actions } = useAnimations(animations, group);

//   useFrame(() => {
//     group.current.getObjectByName("Head").lookAt(state.camera.position); Head follow - not necessary
//   });

  useEffect(() => { 
    actions["Storm"].reset().play(); // Animation active
  }, []);

  return (
    <group ref={group} {...props}>
      <group name="Scene">
        <group name="Armature" position={[0.1, -0.5, 0.7]} rotation={[Math.PI / 3, 0, 0.2]} scale={0.005, 0.005, 0.005}>
          <skinnedMesh
            name="Ch03"
            geometry={nodes.Ch03.geometry}
            material={materials.Ch03_Body}
            skeleton={nodes.Ch03.skeleton}
          />
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/StormAvatar.glb')

export default StormAvatar