/*
Model downloaded from https://www.mixamo.com/#/?page=1&query=running -> saved as .glb file in Blender -> code below Auto-generated by: https://github.com/pmndrs/gltfjsx -> edited to turn it into a working component
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
// import SunnyAvatar from '/models/SunnyAvatar.glb?url'

const SunnyAvatar = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('models/SunnyAvatar.glb');

  console.log(animations);

  animations[0].name = "Sunny";

  const { actions } = useAnimations(animations, group);

//   useFrame(() => {
//     group.current.getObjectByName("Head").lookAt(state.camera.position); Head follow - not necessary
//   });

  useEffect(() => { 
    actions["Sunny"].reset().play(); // Animation active
  }, []);

  return (
    <group ref={group} {...props}>
      <group name="Scene">
        <group name="Armature" position={[0, 0, 1]} rotation={[Math.PI / 2, 0, -0.1]} scale={0.005, 0.005, 0.005}>
          <skinnedMesh
            name="Ch03"
            geometry={nodes.Ch03.geometry}
            material={materials.Ch03_Body}
            skeleton={nodes.Ch03.skeleton}
          />
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/SunnyAvatar.glb')

export default SunnyAvatar